service: now8
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  environment:
    PROVIDER_VARIABLE: I am a provider variable

functions:
  ping:
    handler: functions/ping.main
    events:
      - http:
          path: ping
          method: get


  create_ride:
    handler: functions/create_ride.main
    environment:
      FUNCTION_NAME: create_ride
    events:
      - http:
          path: create_ride
          method: post


plugins:
  - serverless-python-requirements
